# Generated by Django 3.1 on 2023-04-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20230405_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemc',
            old_name='name',
            new_name='review',
        ),
    ]
